fix(useBatteryIsLow): return battery level only if low
react-native-device-info/react-native-device-info pull request #1347
Opened 2021-11-16 15:58 UTC by lisabaut

## Description

Fixes [#1346](https://github.com/react-native-device-info/react-native-device-info/issues/1346)

The hook `useBatteryIsLow` returns the current battery level on initial rendering - even if the current battery level is not considered as low (Android < 0.15, iOS < 0.20);

With removing the initial value from the useEffect hook on initial rendering, the returned value remains `null` until the listener `RNDeviceInfo_batteryLevelIsLow`  detects the first callback for a low battery status.

### Testing
On iOS simulator the battery level is always `-1`.
On Android emulator the battery level is always `1`.
At least for me.
I therefore tested it on an external physical device too. See the video in the linked ticket above. 

I did not find dedicated tests for the hooks. Let me know if I missed something.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Windows |    ✅    |

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [ ] I added the documentation in `README.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

2021-11-16 16:08 UTC, schie reviewed
I, for the most part, agree w/ this change. 

Would adding a check for the initial value behoove us? What I mean is, _'after getting the initial value, then check to see if it is below the threshold'_ ?

2021-11-16 16:11 UTC, schie commented
As as aside, this hook seems very weird. From just reading the name of it, I was assuming it would just spit-out a boolean rather than a number, but `¯\_(ツ)_/¯`

2021-11-16 16:11 UTC, schie approved these changes

2021-11-16 16:39 UTC, mikehardy requested changes
@schie 
> I, for the most part, agree w/ this change.
> 
> Would adding a check for the initial value behoove us? What I mean is, _'after getting the initial value, then check to see if it is below the threshold'_ ?

That was my first take as well, From https://github.com/react-native-device-info/react-native-device-info/issues/1346#issuecomment-969169742

> if we remove the lines completely, won't that miss the case where it should fire when the battery actually is low, vs waiting for a battery level change event to trigger evaluation vs the low battery thresholds ?

So that's 2 immediate concerns registered about the same thing. I believe the API won't feel right unless there is a check on initial loading, .15 for android .20 for ios as noted - the API should trigger if the battery is already low during first use

Once that's in I can merge and release this, and thank you!

@schie I agree the API is a bit wonky but if you think of it from a javascript perspective, null vs the info you want is still false-y and truth-y, which is kind of javascript-y even if "yes, weird..."

2021-11-17 18:16 UTC, lisabaut commented
I added a helper function which does the check again if the current battery level is actually low:
- Android < 0.15
- iOS/web < 0.2

If `true` the initial value is set to the state and returned by the hook.
If `false` the default return value remains `null`. 

Please note that testing on iOS simulators is not really helpful as the battery level is always `-1`. 
I did not add an additional check for that (e.g. `return level > 0 && level < 0.2`).
On Android emulators the battery level is always `1`.

<img width="847" alt="Bildschirmfoto 2021-11-17 um 18 50 14" src="https://user-images.githubusercontent.com/11243967/142258138-12323d5d-5e71-4369-ac31-e0b0077cc6b9.png">

2021-11-17 22:12 UTC, mikehardy approved these changes
Interesting, this bit:

>  If false the default return value remains null.
> Please note that testing on iOS simulators is not really helpful as the battery level is always -1.

Collides a little bit with the stated "default" values of the APIs from the README:

> Note that many APIs are platform-specific. If there is no implementation for a platform, then the "default" return values you will receive are "unknown" for string, -1 for number, and false for boolean. Arrays and Objects will be empty ([] and {} respectively).

However, this is the way it was so leaving it that way (null as default here) is a less-breaking change, and at least it maps along with -1 to "false-y" in javascript so it still evaluates the same on iOS simulator.

Kind of a mess but nothing that you did @lisabaut - this should have been a better API from the start, and I was here to review it so that's on me

I think this change handles the initial hook and subsequent events really well now and I appreciate it! Definitely an improvement over the previous behavior

2021-11-17 22:13 UTC, merged