Extend the getVersion documentation
react-native-device-info/react-native-device-info pull request #1412
Opened 2022-05-06 06:13 UTC by mtnt

## Description

Fixes #1411

## Checklist

* [ ] I have tested this on a device/simulator for each compatible OS
* [X] I added the documentation in `README.md`
* [ ] I updated the typings files (`privateTypes.ts`, `types.ts`)
* [ ] I added a sample use of the API (`example/App.js`)

2022-05-06 13:55 UTC, schie approved these changes

2022-05-06 13:57 UTC, schie requested changes
sorry, Fat-fingered 'approve' option

2022-05-17 07:36 UTC, PhaseboyTA reviewed
To go or not to go..

2022-05-17 07:36 UTC, PhaseboyTA commented on extendGetVersionDoc
>  let version = DeviceInfo.getVersion();
) L4

2022-06-02 19:03 UTC, mikehardy approved these changes
I just committed @schie suggestion and now this looks good to me, thanks!

2022-06-04 16:31 UTC, merged

2022-06-04 17:04 UTC, jbyj commented
@mikehardy Did you intend to nuke the readme as this renames it to [extendGetVersionDoc](https://github.com/react-native-device-info/react-native-device-info/pull/1412/files/ae351997afbf3321732d1cff3e8466705d27dd5c#diff-e58800435b2e23b8d660db9dad2e10c5d8e3ca4f93f5208495424b21786cc07c)?

2022-06-04 18:43 UTC, mikehardy commented
Oh 💩 ! Nope. Thanks for checking, I'm out at lunch now but will look after

2022-06-04 19:20 UTC, mikehardy commented
Fixed, thanks again @jbyj